:toc: macro
:toclevels: 5
:figure-caption!:

:capybara_link: link:https://github.com/teamcapybara/capybara[Capybara]
:cuprite_link: link:https://cuprite.rubycdp.com[Cuprite]
:dry_link: link:https://dry-rb.org[Dry RB]
:dotenv_link: link:https://github.com/bkeepers/dotenv[Dotenv]
:dotfiles_link: link:https://alchemists.io/projects/dotfiles[Dotfiles]
:hanami_link: link:https://hanamirb.org[Hanami]
:htmx_link: link:https://alchemists.io/projects/htmx[HTMX]
:pg_link: link:https://github.com/ged/ruby-pg[pg]
:puma_link: link:https://puma.io[Puma]
:rack_link: link:https://github.com/rack/rack[Rack]
:rom_link: link:https://rom-rb.org[ROM]
:rubysmith_link: link:https://alchemists.io/projects/rubysmith[Rubysmith]

= Hanamismith

Hanamismith is a Command Line Interface (CLI) for smithing Hanami projects. Perfect for when you need a professional and robust tool for building new project skeletons. To quote from the {dry_link} and {hanami_link} teams:
____
If you're looking for new ways to build maintainable, secure, faster and testable Ruby applications, you're in for a treat. *Hanami is built for people like you*.

Whether you're a total beginner or an experienced developer, *this learning process may still be hard*. Over time, we become used to certain things, and it can be painful to change. *But without change, there is no challenge* and without challenge, there is no growth.
____

Welcome to the modern age of web development. This gem will help you get up and running as quickly as possible. 🚀

toc::[]

== Features

* Built atop {rubysmith_link} for building project skeleton.
* Uses {dry_link} for functional programming.
* Uses {hanami_link} for web application development.
* Uses {htmx_link} for proper Hypermedia REST APIs (i.e. HTML over the wire) so you can write less code and avoid bloated JavaScript stacks.
* Uses {pg_link} coupled with {rom_link} for database management.
* Uses {rack_link}, specifically: `Rack::Deflater`, `Rack::Static`, and link:https://github.com/rack/rack-attack[Rack::Attack].
* Uses {puma_link} as the default web server and fully configured for local and production environments.
* Uses {capybara_link} with {cuprite_link} (driver) for full, headless, feature testing.
* Uses {dotenv_link} for managing your environment configurations.
* Provides support for Continuous Integration systems like link:https://circleci.com[Circle CI] (default) and link:https://docs.github.com/en/actions[GitHub Actions].
* Provides the `/up` health check endpoint via the `Health` slice.
* Disables link:https://github.com/ruby/irb[IRB] console autocomplete when used in production-like environments. You can re-enable IRB autocomplete by setting `IRB_USE_AUTOCOMPLETE=true` before launching your console in non development or test environments.

== Requirements

. link:https://www.ruby-lang.org[Ruby].

== Setup

To install _with_ security, run:

[source,bash]
----
# 💡 Skip this line if you already have the public certificate installed.
gem cert --add <(curl --compressed --location https://alchemists.io/gems.pem)
gem install hanamismith --trust-policy HighSecurity
----

To install _without_ security, run:

[source,bash]
----
gem install hanamismith
----

== Usage

=== Command Line Interface (CLI)

From the command line, type: `hanamismith --help`

....
USAGE
  hanamismith [OPTIONS]
  hanamismith COMMAND [OPTIONS]

OPTIONS
  -v, --version            Show version.
  -h, --help [COMMAND]     Show this message.

COMMANDS
  config                   Manage configuration.
                           Path is dynamic per current directory.
  build                    Build new project.
....

The core functionality of this gem centers around the `build` command and associated flags. The build options allow you to further customize the kind of gem you want to build. Most build options are enabled by default. For detailed documentation on all supported flags, see the link:https://alchemists.io/projects/rubysmith/#_build[Rubysmith] documentation.

=== Configuration

This gem can be configured via a global configuration:

....
$HOME/.config/hanamismith/configuration.yml
....

It can also be configured via link:https://alchemists.io/projects/xdg[XDG] environment
variables.

The default configuration is everything provided in the
link:https://alchemists.io/projects/rubysmith/#_configuration[Rubysmith]. It is recommended that you provide common URLs for your project which would be all keys found in this section:

[source,yaml]
----
:project:
  :url:
    # Add sub-key values here.
----

When these values exist, you'll benefit from having this information added to your generated project documentation. Otherwise -- if these values are empty -- they are removed from new project generation entirely.

=== Workflows

When implementing and testing your project locally, a typical workflow might be:

[source,bash]
----
# Build new project
hanamismith build --name demo

# Run code quality and test coverage checks
cd demo
bin/setup
bin/hanami db create
HANAMI_ENV=test hanami db create
bin/rake

# Develop (red, green, refactor)
bin/guard
git commit  # (repeat until finished with implementation)

# Run: With Overmind (recommended)
overmind start --port-step 10 --procfile Procfile.dev

# Run: Without Overmind
bin/hanami server

# Deploy
git push

# Help
bin/hanami --help
----

Once the server is running you can visit (or ping) the following endpoints:

* `/`: The default welcome page.
* `/up`: The health status of the application. This will be _green_ (200 OK) when the server is up or _red_ (503 Service Unavailable) when the server is down.

=== Aliases

For link:https://www.gnu.org/software/bash[Bash] users -- or other shell users -- you might find the following aliases helpful in reducing terminal keystrokes when using this gem:

[source,bash]
----
alias hsb="hanamismith build --name"
alias hse="hanamismith config --edit"
alias hsh="hanamismith --help"
----

The above is what I use via my {dotfiles_link} project.

=== Demonstrations

For a fully working demonstration application -- as built by this gem -- check out the link:https://github.com/bkuhlmann/hemo[Hemo] project. Here's a quick screencast overview of this demonstration application in action:

video::https://alchemists.io/videos/projects/hemo/demo.mp4[poster=https://alchemists.io/images/projects/hemo/demo.png,width=800,height=450,role=focal_point]

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/hanamismith
cd hanamismith
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== link:https://alchemists.io/policies/license[License]

== link:https://alchemists.io/policies/security[Security]

== link:https://alchemists.io/policies/code_of_conduct[Code of Conduct]

== link:https://alchemists.io/policies/contributions[Contributions]

== link:https://alchemists.io/projects/hanamismith/versions[Versions]

== link:https://alchemists.io/community[Community]

== Credits

* Built with link:https://alchemists.io/projects/gemsmith[Gemsmith].
* Engineered by link:https://alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
